### PR TITLE
added background gif for homepage and set path to image

### LINKED ISSUE #194: Make sure all assets are in local
The giphy in the home page is from https://media.giphy.com/media/5xtDarqiAfN6mqPwdyw/giphy.gif

Download it locally instead of linking an online asset

Also check other instances (if present) of assets that are referred externally

### PR DESCRIPTION
**Pull request by DanBenesh**
Resolves #194

# Description

Added the asset from giphy, and changed path. Could not find any other external assets.

### CODE REVIEW

**Review by DanBenesh — COMMENTED** [review]
Please review and let me know if any other assets are referrenced externally. Thanks

**Review by ralphgregorio — COMMENTED** [review]
will approve once merge conflicts are resolved. I also noticed you are working from devbackend which is the wrong branch. We are working from development branch not devbackend

**Comment by DanBenesh** [comment]
I realized that it was the wrong branch after making the PR. Should I close and resubmit with the development branch?

**Review by ralphgregorio — APPROVED** [review]
looks good! ready to merge

**Pull request merged**
